// ── Knowledge Center ─────────────────────────────────────────────────────────
// Curated agronomic reference: turf disease / weed / insect profiles (keyed to
// the same ids the risk models use, so a risk score can link straight to "what
// it is and what to do"), plus the essential plant nutrients. General guidance —
// always follow the product label and local extension recommendations.

// kind: 'Disease' | 'Weed' | 'Insect'
// grasses: lowercase tokens ('bent','poa','rye','bluegrass','fescue','bermuda',
// 'zoysia') or ['any'] — matches lib/pests.js so the two stay in sync.
export const PROFILES = [
  {
    id: 'dollar_spot', name: 'Dollar spot', kind: 'Disease', grasses: ['any'],
    pathogen: 'Clarireedia spp. (formerly Sclerotinia homoeocarpa)',
    blurb: 'The most common and costly disease on cool-season greens and fairways. Small, silver-dollar-sized straw-colored spots that can merge into larger blighted areas.',
    favoredBy: 'Warm days (60–85°F), mild humid nights with heavy dew, long leaf-wetness periods, and low nitrogen. Classic warm-day/cool-humid-night pattern.',
    identify: 'Sunken, bleached spots ~1–3" across; hourglass lesions on leaf blades with tan centers and reddish-brown borders. White cottony mycelium in early-morning dew.',
    manage: 'Keep nitrogen adequate (low N raises risk). Remove dew early (mow, roll, or drag). Rotate FRAC groups (DMI, SDHI, nitrile) to avoid resistance — it develops readily. Extend intervals in cool/dry spells.',
  },
  {
    id: 'brown_patch', name: 'Brown patch', kind: 'Disease', grasses: ['any'],
    pathogen: 'Rhizoctonia solani',
    blurb: 'Circular patches in hot, humid weather — especially on tall fescue, ryegrass and bentgrass.',
    favoredBy: 'Warm nights (≥60°F), warm days (≥80°F), high humidity and extended leaf wetness. High nitrogen and lush growth worsen it.',
    identify: 'Roughly circular patches a few inches to several feet; a grayish "smoke ring" at the margin in the morning on close-cut turf. Tan, water-soaked lesions on leaves.',
    manage: 'Avoid excess nitrogen in summer. Improve air movement and drainage; water early so leaves dry by evening. Preventive fungicides (SDHI, QoI, DMI) on a rotation during high-risk stretches.',
  },
  {
    id: 'pythium', name: 'Pythium blight', kind: 'Disease', grasses: ['bent', 'poa', 'rye', 'bluegrass', 'fescue'],
    pathogen: 'Pythium spp.',
    blurb: 'A fast, destructive disease that can wipe out turf overnight in hot, saturated conditions. Follows drainage and mowing patterns.',
    favoredBy: 'Hot days (≥86°F), warm nights (≥68°F), very high humidity and standing water / poor drainage. Spreads along water flow and equipment.',
    identify: 'Greasy, water-soaked, dark patches that collapse quickly; cottony white mycelium in early morning. Often in streaks following surface drainage.',
    manage: 'Improve drainage and airflow; avoid evening irrigation and mowing wet turf. This is an oomycete — needs Pythium-specific chemistry (e.g. mefenoxam, cyazofamid, phosphonates, ethazole); most fungicides do not touch it. Act preventively before hot, wet spells.',
  },
  {
    id: 'anthracnose', name: 'Anthracnose', kind: 'Disease', grasses: ['poa', 'bent'],
    pathogen: 'Colletotrichum cereale',
    blurb: 'Foliar blight and basal rot, most damaging on stressed annual bluegrass greens.',
    favoredBy: 'Stress — low nitrogen, low mowing, drought, compaction. Warm, humid weather. Poa annua under summer stress is most vulnerable.',
    identify: 'Yellow-to-bronze irregular patches; black fruiting bodies (acervuli) with tiny spines visible under a hand lens. Basal rot blackens the crown/stem base.',
    manage: 'Reduce stress: raise mowing height slightly, keep nitrogen adequate, relieve compaction, manage moisture. Rotate fungicides (QoI, DMI, SDHI, benzimidazole) preventively on Poa greens.',
  },
  {
    id: 'gray_leaf', name: 'Gray leaf spot', kind: 'Disease', grasses: ['rye', 'fescue'],
    pathogen: 'Pyricularia grisea',
    blurb: 'Explosive blighting of perennial ryegrass (and tall fescue), especially late summer.',
    favoredBy: 'Hot days (≥86°F), warm nights (≥70°F), prolonged leaf wetness/humidity. Newly seeded rye and high-nitrogen turf are most at risk.',
    identify: 'Gray-to-tan leaf lesions with dark borders; twisted, "fishhook" leaf tips. Rapid thinning that can look like drought.',
    manage: 'Avoid high nitrogen in late summer; water to minimize leaf wetness. Preventive fungicides (QoI, DMI) during the risk window — resistance to QoI is common, so rotate.',
  },
  {
    id: 'microdochium', name: 'Microdochium patch', kind: 'Disease', grasses: ['bent', 'poa', 'rye', 'fescue', 'bluegrass'],
    pathogen: 'Microdochium nivale',
    blurb: 'Cool-season patch disease (also called pink snow mold) active in cold, wet weather — no snow required.',
    favoredBy: 'Cool temps (32–55°F), high humidity, prolonged leaf wetness and rain. Fall through spring; under snow cover too.',
    identify: 'Small water-soaked spots enlarging to tan/pink patches a few inches across; pinkish mycelium at margins in wet conditions.',
    manage: 'Avoid late-fall nitrogen flushes; improve drainage and airflow; remove leaf debris. Preventive fungicides ahead of cold, wet periods and before snow cover.',
  },
  {
    id: 'large_patch', name: 'Large patch', kind: 'Disease', grasses: ['zoysia', 'bermuda'],
    pathogen: 'Rhizoctonia solani AG2-2 LP',
    blurb: 'A warm-season-turf disease (zoysia, bermuda) active in the transition seasons.',
    favoredBy: 'Soil ~50–70°F with moisture, in spring green-up and fall dormancy. Excess water and thatch worsen it.',
    identify: 'Large circular patches (often several feet) with orange-firing at the advancing edge; rotted leaf sheaths that pull away easily.',
    manage: 'Time preventive fungicides to soil temperature in fall (and spring). Reduce thatch, improve drainage, avoid spring nitrogen before full green-up.',
  },
  {
    id: 'summer_patch', name: 'Summer patch', kind: 'Disease', grasses: ['poa', 'bluegrass', 'fescue', 'bent'],
    pathogen: 'Magnaporthiopsis poae',
    blurb: 'A root-infecting patch disease of Poa annua, Kentucky bluegrass and fine fescue that shows up as summer heat arrives.',
    favoredBy: 'Root infection begins as soil warms through ~65°F at 2" in spring; symptoms appear later under summer heat/drought stress.',
    identify: 'Rings and crescents of yellow-to-straw turf, often with a green tuft in the center ("frog-eye"). Dark, rotted roots.',
    manage: 'Preventive fungicides applied in spring at the soil-temperature window (drenched to the roots) — curative sprays in summer are far less effective. Raise mowing height, avoid drought stress, use acidifying N.',
  },
  {
    id: 'spring_dead_spot', name: 'Spring dead spot', kind: 'Disease', grasses: ['bermuda'],
    pathogen: 'Ophiosphaerella spp.',
    blurb: 'The most serious disease of bermudagrass — circular dead patches that appear at spring green-up.',
    favoredBy: 'Infection in fall as soil cools through ~55–70°F; damage revealed in spring. Worse on high-maintenance, heavily thatched, poorly drained bermuda.',
    identify: 'Bleached, sunken circular patches (inches to feet) that stay dead into spring while surrounding turf greens up; dark rotted roots and stolons.',
    manage: 'Fall fungicides at the soil-temperature window are the key preventive step. Reduce thatch, improve drainage, avoid late-season high nitrogen, use ammonium-based N.',
  },
  {
    id: 'crabgrass', name: 'Crabgrass', kind: 'Weed', grasses: ['any'],
    pathogen: 'Digitaria spp.',
    blurb: 'Summer annual grassy weed that germinates in spring and thrives in thin, hot turf.',
    favoredBy: 'Soil warming through ~55°F (≈ forsythia bloom); thin turf, low mowing, compaction and moist surfaces.',
    identify: 'Light-green, coarse, spreading grass with finger-like seedheads; prostrate growth that roots at nodes.',
    manage: 'Apply a pre-emergent before germination (soil ~55°F / early crabgrass GDD). Maintain dense turf and adequate mowing height. Post-emergent options exist but are easiest on young plants.',
  },
  {
    id: 'goosegrass', name: 'Goosegrass', kind: 'Weed', grasses: ['any'],
    pathogen: 'Eleusine indica',
    blurb: 'Tough summer annual that germinates about two weeks after crabgrass and tolerates close mowing and compaction.',
    favoredBy: 'Soil warming past ~60–65°F; compacted, wet, thin areas — cart paths, approaches, worn collars.',
    identify: 'Flattened "goosefoot" rosette with a white-to-silver center; zipper-like seedheads. Very tough to pull.',
    manage: 'Pre-emergent timed a bit later than crabgrass (soil ~60–65°F). Relieve compaction and improve drainage. Post-emergent control is difficult — treat young plants.',
  },
  {
    id: 'poa_germ', name: 'Annual bluegrass (Poa annua)', kind: 'Weed', grasses: ['any'],
    pathogen: 'Poa annua',
    blurb: 'The classic invasive/weed grass of cool-season turf — prolific seedhead producer that fills gaps.',
    favoredBy: 'Germinates as soil cools below ~70°F (mainly a fall flush, favored 50–64°F); thrives in moist, compacted, close-cut turf.',
    identify: 'Light-green, fine-bladed clumps with boat-shaped leaf tips; abundant whitish seedheads even at low mowing.',
    manage: 'Fall pre-emergent ahead of the germination window; reduce compaction and surface moisture. Where Poa is the desired surface, manage it agronomically instead.',
  },
  {
    id: 'abw', name: 'Annual bluegrass weevil (ABW)', kind: 'Insect', grasses: ['poa', 'bent'],
    pathogen: 'Listronotus maculicollis',
    blurb: 'A damaging insect of Poa annua and bentgrass on greens, tees and fairway edges in the Northeast/transition zone.',
    favoredBy: 'Adults migrate in early spring; multiple overlapping generations through summer. Damage concentrates on Poa-dominant, close-cut turf.',
    identify: 'Small yellow-to-straw patches spreading from collars/edges; larvae (legless, cream with brown head) in the crown/thatch; adults are small black weevils.',
    manage: 'Target the most susceptible stage: adults at first migration, or small larvae (egg-lay window by GDD). Rotate insecticide chemistry (IRAC groups). Monitor with soap flushes / thatch checks.',
  },
  {
    id: 'white_grub', name: 'White grubs', kind: 'Insect', grasses: ['any'],
    pathogen: 'Scarab larvae (Japanese beetle, chafers, etc.)',
    blurb: 'Root-feeding larvae that cause wilting, thinning and turf that pulls up like carpet; secondary animal digging.',
    favoredBy: 'Adult flight in early summer; eggs hatch to young grubs in mid-to-late summer — the best treatment window.',
    identify: 'C-shaped white larvae in the top few inches of soil; irregular wilting/browning that peels back with no roots. Skunks/birds digging.',
    manage: 'Preventive products (e.g. chlorantraniliprole) applied ahead of egg hatch; curative products against young grubs. Confirm thresholds by scouting (cup-cutter counts). Water in soil-applied insecticides.',
  },
  {
    id: 'billbug', name: 'Bluegrass billbug', kind: 'Insect', grasses: ['bluegrass', 'rye', 'fescue'],
    pathogen: 'Sphenophorus parvulus',
    blurb: 'A weevil whose larvae hollow out stems and feed on crowns, causing drought-like thinning that resists watering.',
    favoredBy: 'Adults active in spring; larvae feed early-to-mid summer. Damage often mistaken for drought or dormancy.',
    identify: 'Adult billbugs (small, snout-nosed weevils) crossing paths in spring; stems break easily and are packed with fine, sawdust-like frass. Turf pulls up at the crown.',
    manage: 'Target adults in spring or small larvae early summer (by GDD). Endophyte-enhanced grasses resist billbugs; maintain healthy, non-drought-stressed turf.',
  },

  // ── More diseases ──────────────────────────────────────────────────────────
  {
    id: 'take_all_patch', name: 'Take-all patch', kind: 'Disease', grasses: ['bent'],
    pathogen: 'Gaeumannomyces graminis var. avenae',
    blurb: 'A root and crown rot of creeping bentgrass, common on newer high-pH sand greens.',
    favoredBy: 'Cool, wet spring and fall; high soil pH; sand rootzones low in manganese; recently established bentgrass.',
    identify: 'Reddish-bronze rings and patches (inches to feet) that thin out, often with weeds in the center; dark, rotted roots.',
    manage: 'Acidify with ammonium-based N and add manganese; avoid liming. Preventive DMI/QoI fungicides in spring and fall drenched to the roots; improve drainage.',
  },
  {
    id: 'necrotic_ring_spot', name: 'Necrotic ring spot', kind: 'Disease', grasses: ['bluegrass', 'fescue'],
    pathogen: 'Ophiosphaerella korrae',
    blurb: 'A root-rotting patch disease of Kentucky bluegrass (and fine fescue), often on sodded lawns.',
    favoredBy: 'Cool, moist conditions in spring and fall; stress and heavy thatch; 2–4 years after sodding.',
    identify: 'Straw-colored rings and crescents 6–24" with a green tuft in the center ("frog-eye"); dark, rotted roots.',
    manage: 'Reduce thatch and compaction, use light frequent N, keep moisture even. DMI fungicides in spring/fall drenched in; overseed with resistant/fescue blends.',
  },
  {
    id: 'fairy_ring', name: 'Fairy ring', kind: 'Disease', grasses: ['any'],
    pathogen: 'Various soil basidiomycetes (Marasmius, Lycoperdon, etc.)',
    blurb: 'Rings or arcs of dark-green, stimulated, or dead turf — sometimes with mushrooms — caused by soil fungi feeding on organic matter.',
    favoredBy: 'Soils high in undecomposed organic matter/thatch; drought and hydrophobic (water-repellent) rootzones make it worse.',
    identify: 'Circles/arcs of lush dark-green or dead turf; puffballs or mushrooms after rain; soil under the ring often repels water.',
    manage: 'Mask stimulated rings with N/iron; cure with wetting agents + deep watering and core aeration; DMI/QoI drenches for the damaging types.',
  },
  {
    id: 'red_thread', name: 'Red thread', kind: 'Disease', grasses: ['fescue', 'rye', 'bluegrass'],
    pathogen: 'Laetisaria fuciformis',
    blurb: 'A foliar disease of low-fertility, cool-season turf — mostly cosmetic and rarely kills the plant.',
    favoredBy: 'Low nitrogen, cool (60–75°F), humid weather with long leaf wetness; spring and fall.',
    identify: 'Irregular tan-pink patches; distinctive coral-pink to red thread-like strands ("antlers") binding leaf tips in wet weather.',
    manage: 'Adequate nitrogen usually grows the turf out of it — the primary fix. Fungicides only for severe cases; improve airflow and reduce leaf wetness.',
  },
  {
    id: 'leaf_spot', name: 'Leaf spot / melting-out', kind: 'Disease', grasses: ['bluegrass', 'bent', 'fescue'],
    pathogen: 'Bipolaris / Drechslera spp.',
    blurb: 'A two-phase disease: leaf-spotting in cool weather, then crown/root "melting-out" and thinning as it warms.',
    favoredBy: 'Cool, wet spring (leaf-spot phase), then warm stress (melting-out); excess spring nitrogen and low mowing.',
    identify: 'Purple-brown to black oval leaf lesions with tan centers; later, thinning and browning as crowns rot ("melting out").',
    manage: 'Raise mowing height, avoid heavy spring N, plant resistant cultivars, reduce leaf wetness. Fungicides during the cool leaf-spot phase are most effective.',
  },
  {
    id: 'rust', name: 'Rust', kind: 'Disease', grasses: ['bluegrass', 'rye', 'zoysia'],
    pathogen: 'Puccinia spp.',
    blurb: 'Orange-yellow pustules on leaves — worst on slow-growing, under-fertilized turf in late summer.',
    favoredBy: 'Slow growth, low fertility, heavy dew, warm days/cool nights in late summer and fall; shade.',
    identify: 'Yellow flecks that erupt into orange-red powdery pustules; the orange spores rub off on shoes, mowers and hands.',
    manage: 'Fertilize and water to keep turf growing, mow frequently to remove infected tissue; fungicides only if severe. Resistant cultivars help.',
  },
  {
    id: 'powdery_mildew', name: 'Powdery mildew', kind: 'Disease', grasses: ['bluegrass', 'fescue'],
    pathogen: 'Blumeria graminis',
    blurb: 'A white, dusty leaf coating on shaded, poorly-ventilated cool-season turf — mainly Kentucky bluegrass.',
    favoredBy: 'Shade, poor air movement, cool humid conditions, high nitrogen and lush growth.',
    identify: 'Leaves look dusted with white-gray powder, as if flour was sprinkled on them; heavily infected turf yellows and thins.',
    manage: 'Improve light and airflow (prune, thin), reduce nitrogen, plant shade-tolerant grasses. Fungicides rarely needed.',
  },
  {
    id: 'yellow_patch', name: 'Yellow patch', kind: 'Disease', grasses: ['bent', 'poa', 'bluegrass'],
    pathogen: 'Rhizoctonia cerealis',
    blurb: 'Cool-season "brown patch" — usually a cosmetic ring disease of greens and lawns in cold, wet weather.',
    favoredBy: 'Cold, wet conditions (50–65°F) in late fall through early spring; poor drainage.',
    identify: 'Yellow to bronze rings and patches a few inches to a couple feet across; rarely kills the turf outright.',
    manage: 'Usually recovers as conditions warm; avoid overwatering and improve drainage. Fungicides only if it persists or on high-value greens.',
  },
  {
    id: 'pythium_root', name: 'Pythium root rot', kind: 'Disease', grasses: ['bent', 'poa'],
    pathogen: 'Pythium spp.',
    blurb: 'A root/crown dysfunction of greens (distinct from foliar Pythium blight) that causes vague summer decline.',
    favoredBy: 'Saturated, low-oxygen rootzones; heat and stress; overwatering and poor drainage on push-up or tight greens.',
    identify: 'General thinning, off-color and wilting without clear patches; short, discolored roots. Confirmed by a lab/microscope.',
    manage: 'Fix drainage and aeration, avoid overwatering, relieve compaction. Pythium-specific fungicides (mefenoxam, cyazofamid, phosphonates) drenched to the roots.',
  },
  {
    id: 'typhula_blight', name: 'Gray snow mold (Typhula blight)', kind: 'Disease', grasses: ['bent', 'poa', 'bluegrass', 'rye', 'fescue'],
    pathogen: 'Typhula incarnata / T. ishikariensis',
    blurb: 'A winter patch disease that develops under prolonged snow cover on unfrozen ground.',
    favoredBy: 'Long-lasting snow cover over unfrozen turf; late-fall nitrogen and matted, un-mowed growth going into winter.',
    identify: 'Circular gray-white matted patches appearing at snowmelt; tiny reddish-brown sclerotia (seed-like bodies) on the leaves.',
    manage: 'Preventive fungicides before permanent snow cover; avoid late-season N; keep mowing until dormancy and minimize snow compaction/drifting.',
  },
  {
    id: 'copper_spot', name: 'Copper spot', kind: 'Disease', grasses: ['bent'],
    pathogen: 'Gloeocercospora sorghi',
    blurb: 'A warm-weather spot disease of creeping bentgrass, favored by acidic soils.',
    favoredBy: 'Warm, humid weather with leaf wetness; low soil pH; low fertility.',
    identify: 'Small copper-to-salmon colored spots up to a few inches, sometimes with pink gelatinous spore masses in dew.',
    manage: 'Raise soil pH into range, maintain adequate nitrogen; fungicides (DMI, QoI) for high-value bentgrass if needed.',
  },
  {
    id: 'bacterial_decline', name: 'Bacterial decline / etiolation', kind: 'Disease', grasses: ['bent', 'poa'],
    pathogen: 'Acidovorax avenae',
    blurb: 'An emerging bacterial problem on low-cut greens causing yellow "stretched" shoots and thinning.',
    favoredBy: 'Very low mowing, aggressive PGR use, and summer stress on annual bluegrass / creeping bentgrass greens.',
    identify: 'Yellow, etiolated (elongated, stretched) shoots that stand above the canopy, followed by thinning and decline.',
    manage: 'No reliable curative — manage culturally: raise mowing height, ease off PGRs, reduce stress and moisture. Research on this one is ongoing.',
  },
  {
    id: 'nematodes', name: 'Plant-parasitic nematodes', kind: 'Disease', grasses: ['any'],
    pathogen: 'Sting, root-knot, lance, ring nematodes, etc.',
    blurb: 'Microscopic soil roundworms that feed on roots, causing stubborn summer decline — especially on sand greens.',
    favoredBy: 'Sandy rootzones and greens; summer heat and drought stress amplify damage.',
    identify: 'Irregular thin, off-color, drought-prone areas that resist water and fertilizer; short, stubby, dark roots (root-knot causes galls). Confirmed only by a soil assay.',
    manage: 'Send a soil sample for a nematode count before treating. Promote deep rooting and reduce stress; nematicides only where a labeled product and confirmed threshold justify it.',
  },
  {
    id: 'slime_mold', name: 'Slime mold', kind: 'Disease', grasses: ['any'],
    pathogen: 'Physarum, Fuligo and other saprophytes',
    blurb: 'A harmless, non-parasitic organism that coats leaf blades — alarming to see but never damages turf.',
    favoredBy: 'Warm, wet weather and high surface organic matter; appears suddenly after rain or heavy irrigation.',
    identify: 'Gray, white, purple or yellow crusty/powdery masses coating the grass blades in a patch; brushes off to reveal healthy green turf.',
    manage: 'Cosmetic only — mow, brush, drag, or hose it off. No fungicide needed.',
  },

  // ── More weeds ─────────────────────────────────────────────────────────────
  {
    id: 'dandelion', name: 'Dandelion', kind: 'Weed', grasses: ['any'],
    pathogen: 'Taraxacum officinale',
    blurb: 'The classic broadleaf perennial — a deep taproot and bright flowers that colonize thin, sunny turf.',
    favoredBy: 'Thin, low-density turf; sunny sites; wind-blown seed spreads widely.',
    identify: 'Rosette of jagged ("lion-tooth") leaves, bright yellow flower, white puffball seedhead, thick taproot with milky sap.',
    manage: 'Thick turf is the best defense. Broadleaf herbicides (2,4-D / triclopyr / dicamba blends) work best in fall as plants move sugars to the root.',
  },
  {
    id: 'white_clover', name: 'White clover', kind: 'Weed', grasses: ['any'],
    pathogen: 'Trifolium repens',
    blurb: 'A low, creeping legume that thrives where nitrogen is low and fixes its own — outcompeting hungry turf.',
    favoredBy: 'Low soil nitrogen; open, thin turf. Spreads by stolons and seed.',
    identify: 'Three-leaflet leaves each with a white crescent mark; round white (pinkish) flower heads that attract bees.',
    manage: 'Raise nitrogen to favor the grass. Clopyralid or triclopyr/fluroxypyr blends give good control; repeat as needed.',
  },
  {
    id: 'broadleaf_plantain', name: 'Plantain (broadleaf & buckhorn)', kind: 'Weed', grasses: ['any'],
    pathogen: 'Plantago major / P. lanceolata',
    blurb: 'Rosette-forming broadleaf perennials that flag compacted, worn areas.',
    favoredBy: 'Compaction, wear and wet soils; thin turf.',
    identify: 'Broadleaf plantain: broad oval leaves with prominent parallel veins. Buckhorn: narrow lance-shaped leaves. Both send up "rat-tail" seed stalks.',
    manage: 'Relieve compaction and thicken turf; broadleaf herbicides (2,4-D/triclopyr blends), most effective in fall.',
  },
  {
    id: 'ground_ivy', name: 'Ground ivy (creeping Charlie)', kind: 'Weed', grasses: ['any'],
    pathogen: 'Glechoma hederacea',
    blurb: 'An aggressive creeping perennial of shady, moist areas that mats over thin turf.',
    favoredBy: 'Shade, moist fertile soil, thin turf; spreads by creeping stems that root at nodes.',
    identify: 'Round, scalloped leaves on square stems, a minty odor when crushed, small purple funnel flowers.',
    manage: 'Improve light and drainage; triclopyr-containing blends in fall give the best control — often needs repeat applications.',
  },
  {
    id: 'wild_violet', name: 'Wild violet', kind: 'Weed', grasses: ['any'],
    pathogen: 'Viola spp.',
    blurb: 'A tough, waxy-leaved perennial of shady, moist turf — one of the hardest broadleaf weeds to control.',
    favoredBy: 'Shade and moist soils; spreads by seed and underground rhizomes.',
    identify: 'Heart-shaped, waxy leaves and purple (sometimes white) flowers in spring; forms dense clumps.',
    manage: 'Triclopyr blends applied in fall, usually repeated over seasons. Improve light/drainage; persistence is required.',
  },
  {
    id: 'yellow_nutsedge', name: 'Yellow nutsedge', kind: 'Weed', grasses: ['any'],
    pathogen: 'Cyperus esculentus',
    blurb: 'A fast-growing sedge (not a true grass) of wet areas that outpaces turf between mowings.',
    favoredBy: 'Wet, poorly drained soils; summer heat. Reproduces from underground tubers ("nutlets").',
    identify: 'Glossy yellow-green leaves in sets of three; stiff triangular ("sedges have edges") stems; grows noticeably taller than turf a day after mowing.',
    manage: 'Fix drainage first. Sedge-specific herbicides (halosulfuron, sulfentrazone) target the tubers; repeat to exhaust the nutlets.',
  },
  {
    id: 'foxtail', name: 'Foxtail', kind: 'Weed', grasses: ['any'],
    pathogen: 'Setaria spp.',
    blurb: 'Summer-annual grassy weeds that invade thin, open turf and produce bristly seedheads.',
    favoredBy: 'Thin turf, warm soils, disturbed/newly seeded areas; summer.',
    identify: 'Coarse, upright grass with a soft, cylindrical, bristly seedhead resembling a fox’s tail.',
    manage: 'Pre-emergent at crabgrass timing; maintain dense turf. Post-emergent grass herbicides on young plants.',
  },
  {
    id: 'prostrate_spurge', name: 'Prostrate spurge', kind: 'Weed', grasses: ['any'],
    pathogen: 'Euphorbia (Chamaesyce) maculata',
    blurb: 'A fast summer annual that forms flat mats in hot, thin, compacted turf.',
    favoredBy: 'Heat, compaction and thin turf; germinates through summer.',
    identify: 'Prostrate mat of small paired leaves often with a red spot; stems ooze milky white sap when broken.',
    manage: 'Pre-emergent plus broadleaf post-emergents; relieve compaction and thicken turf to shade it out.',
  },
  {
    id: 'common_chickweed', name: 'Common chickweed', kind: 'Weed', grasses: ['any'],
    pathogen: 'Stellaria media',
    blurb: 'A cool-season winter annual that mats quickly in moist, shaded, thin turf.',
    favoredBy: 'Cool, moist conditions; shade; thin turf. Germinates in fall.',
    identify: 'Small smooth oval leaves on trailing stems, tiny white star-shaped flowers with deeply notched petals.',
    manage: 'Fall or early-spring broadleaf herbicides; keep turf dense. (Note: mouse-ear chickweed is a hairier perennial cousin.)',
  },
  {
    id: 'henbit', name: 'Henbit', kind: 'Weed', grasses: ['any'],
    pathogen: 'Lamium amplexicaule',
    blurb: 'A winter-annual broadleaf that carpets thin turf with purple flowers in early spring.',
    favoredBy: 'Cool season; open, moist, fertile soil; germinates in fall.',
    identify: 'Square stems, rounded scalloped leaves that clasp the stem, whorls of small purple-pink tubular flowers in spring.',
    manage: 'Fall pre-/post-emergent broadleaf control before it flowers and seeds; thicken turf.',
  },
  {
    id: 'prostrate_knotweed', name: 'Prostrate knotweed', kind: 'Weed', grasses: ['any'],
    pathogen: 'Polygonum aviculare',
    blurb: 'A summer annual that is a classic indicator of compacted soil — often the first weed along cart paths and worn areas.',
    favoredBy: 'Severe compaction and high-traffic, worn areas; germinates very early, before crabgrass.',
    identify: 'Wiry, tough, prostrate stems radiating from a central taproot with small blue-green oval leaves and swollen leaf joints.',
    manage: 'Relieve compaction (aerate) — it will keep coming back otherwise. Apply pre-emergent very early (ahead of crabgrass) and post-emergents on young plants.',
  },
  {
    id: 'nimblewill', name: 'Nimblewill', kind: 'Weed', grasses: ['bent', 'bluegrass', 'fescue'],
    pathogen: 'Muhlenbergia schreberi',
    blurb: 'A warm-season perennial grass that invades cool-season turf and browns out conspicuously in fall.',
    favoredBy: 'Moist, shaded areas; spreads by wiry above-ground stolons.',
    identify: 'Fine, gray-green wiry patches with short leaves; goes tan/dormant with the first frost while surrounding turf stays green.',
    manage: 'Hard to control selectively. Tenacity (mesotrione) offers some suppression; otherwise spot-treat with a non-selective and reseed.',
  },
  {
    id: 'dallisgrass', name: 'Dallisgrass', kind: 'Weed', grasses: ['any'],
    pathogen: 'Paspalum dilatatum',
    blurb: 'A coarse perennial bunchgrass that forms unsightly clumps and sprawling seedheads.',
    favoredBy: 'Wet, low areas and warm climates; persists from short rhizomes year after year.',
    identify: 'Coarse light-green clumps growing in a ring; tall seed stalks with finger-like branches bearing dark, hairy-spotted seeds.',
    manage: 'Tough perennial — spot-treat with a non-selective and reseed, or repeated selective post-emergents where labeled; maintain dense turf.',
  },
  {
    id: 'kyllinga', name: 'Green kyllinga', kind: 'Weed', grasses: ['any'],
    pathogen: 'Kyllinga spp.',
    blurb: 'A low, mat-forming sedge of wet areas that tolerates close mowing better than nutsedge.',
    favoredBy: 'Wet, poorly drained, low-lying areas; summer heat; spreads by rhizomes and seed.',
    identify: 'Dense dark-green mat of fine sedge leaves; round green seedheads held just above the mat; triangular stems.',
    manage: 'Improve drainage; sedge herbicides (halosulfuron, sulfentrazone) with repeat applications — it is persistent.',
  },
  {
    id: 'oxalis', name: 'Yellow woodsorrel (oxalis)', kind: 'Weed', grasses: ['any'],
    pathogen: 'Oxalis stricta',
    blurb: 'A clover-like broadleaf that spreads by explosively-ejected seed into thin turf.',
    favoredBy: 'Thin turf, warm weather; disturbed and container-grown areas.',
    identify: 'Three heart-shaped leaflets (like clover but notched), small five-petal yellow flowers, and okra-like seed pods that pop when touched.',
    manage: 'Broadleaf herbicides (triclopyr blends) on actively growing plants; thicken turf to shade it out.',
  },
  {
    id: 'moss', name: 'Moss (silvery thread moss)', kind: 'Weed', grasses: ['bent', 'poa'],
    pathogen: 'Bryum argenteum and others',
    blurb: 'Not a weed grass but an opportunist that colonizes weak, wet greens where turf has thinned.',
    favoredBy: 'Low fertility, excess moisture, compaction, low mowing, shade and poor airflow — anywhere the turf is thin.',
    identify: 'Low green-to-silvery mat of tiny moss plants filling thin or bare spots, especially on greens.',
    manage: 'Fix the cause: light, drainage, airflow, fertility and aeration. Spot treatments (carfentrazone, iron/iron sulfate, or baking soda) knock it back, but agronomics keep it out.',
  },
  {
    id: 'algae', name: 'Algae', kind: 'Weed', grasses: ['bent', 'poa'],
    pathogen: 'Cyanobacteria / green algae',
    blurb: 'A slimy black-green crust that forms on chronically wet, thin greens and low areas, sealing the surface.',
    favoredBy: 'Standing water, high humidity, shade, poor airflow and thin turf; warm weather.',
    identify: 'Dark green-to-black slimy film when wet that dries to a black, cracked crust; the surface sheds water.',
    manage: 'Improve drainage, airflow and light; cut back irrigation. Chlorothalonil/mancozeb or hydrogen-dioxide products help, but drying the site out is the real fix.',
  },

  // ── More insects ───────────────────────────────────────────────────────────
  {
    id: 'black_cutworm', name: 'Black cutworm', kind: 'Insect', grasses: ['bent', 'poa'],
    pathogen: 'Agrotis ipsilon',
    blurb: 'A caterpillar that chews pockmarks into greens and tees, feeding at night from burrows.',
    favoredBy: 'Summer; adult moths lay eggs on greens; damage tracks warm nights.',
    identify: 'Pencil-eraser-sized sunken "ballmark" pockets on greens; greasy gray-black larvae that curl into a C when disturbed; birds pecking.',
    manage: 'Monitor with a soap flush. Treat young larvae with a pyrethroid or anthranilic diamide; mowing and clipping removal takes out eggs.',
  },
  {
    id: 'sod_webworm', name: 'Sod webworm', kind: 'Insect', grasses: ['any'],
    pathogen: 'Crambus / Parapediasia spp.',
    blurb: 'Larvae of small "lawn moths" that notch leaves and thin sunny, stressed turf.',
    favoredBy: 'Hot, dry, sunny areas in mid-to-late summer; stressed turf.',
    identify: 'Small ragged brown patches and notched/chewed leaves; tan larvae in silk-lined burrows; buff-colored moths that flutter up at dusk in a zig-zag.',
    manage: 'Confirm with a soap flush. Bt, diamides or pyrethroids on young larvae in late afternoon; irrigate to reduce stress.',
  },
  {
    id: 'fall_armyworm', name: 'Fall armyworm', kind: 'Insect', grasses: ['any'],
    pathogen: 'Spodoptera frugiperda',
    blurb: 'A migratory caterpillar that can strip large areas of turf almost overnight in late summer.',
    favoredBy: 'Late summer/fall; moves north on storm fronts in big numbers.',
    identify: 'Sudden, spreading defoliation; green-to-brown striped larvae with a light inverted "Y" on the head; birds feeding heavily.',
    manage: 'Scout regularly late summer — they arrive fast. Treat small larvae with a diamide or pyrethroid; irrigation before treatment helps.',
  },
  {
    id: 'hairy_chinch_bug', name: 'Hairy chinch bug', kind: 'Insect', grasses: ['bluegrass', 'fescue', 'bent'],
    pathogen: 'Blissus leucopterus hirtus',
    blurb: 'A sap-sucking bug that causes drought-like patches in hot, sunny cool-season turf.',
    favoredBy: 'Hot, dry summers; sunny, south-facing slopes; thatchy turf.',
    identify: 'Irregular yellowing-to-brown patches that spread and don’t green up with water; small black-and-white adults and red nymphs at the thatch line (confirm with a float/coffee-can test).',
    manage: 'Water stressed turf, reduce thatch, use endophytic grasses. Pyrethroid or diamide if counts exceed threshold.',
  },
  {
    id: 'mole_cricket', name: 'Mole cricket', kind: 'Insect', grasses: ['bermuda', 'zoysia'],
    pathogen: 'Scapteriscus spp.',
    blurb: 'A burrowing insect that tunnels through and uproots warm-season turf on sandy southern sites.',
    favoredBy: 'Sandy soils and warm-season turf in the southern U.S.; peak damage from summer nymphs.',
    identify: 'Spongy, raised tunneling that dislodges soil and loosens turf so it lifts easily; a soap flush brings the crickets to the surface.',
    manage: 'Target small nymphs in early-to-mid summer with baits or diamides; use soap flushes to time treatment. Mature adults are hard to kill.',
  },
  {
    id: 'european_crane_fly', name: 'European crane fly (leatherjackets)', kind: 'Insect', grasses: ['bent', 'poa', 'rye', 'bluegrass', 'fescue'],
    pathogen: 'Tipula spp.',
    blurb: 'The root-and-crown-feeding larvae ("leatherjackets") of a large mosquito-like fly, damaging in cool, wet regions.',
    favoredBy: 'Cool, wet climates (Pacific Northwest, Northeast); larvae feed fall through spring.',
    identify: 'Thinning and bare patches in spring; fat, gray-brown, legless larvae with tough skin feeding on roots/crowns at night; birds probing.',
    manage: 'Sample to confirm thresholds. Treat young larvae in fall with a diamide or pyrethroid; healthy, well-drained turf tolerates more.',
  },
  {
    id: 'greenbug_aphid', name: 'Greenbug aphid', kind: 'Insect', grasses: ['bluegrass'],
    pathogen: 'Schizaphis graminum',
    blurb: 'A tiny aphid that injects toxic saliva, burning out patches of Kentucky bluegrass, often under trees.',
    favoredBy: 'Shade (especially under trees); cool conditions; Kentucky bluegrass.',
    identify: 'Yellow-to-orange patches, frequently beneath tree canopies, with a scorched burnt-orange center; clusters of small pale-green aphids on the blades.',
    manage: 'Usually a localized spot problem — insecticidal soap or a systemic where warranted; healthy turf recovers.',
  },
  {
    id: 'bermudagrass_mite', name: 'Bermudagrass mite', kind: 'Insect', grasses: ['bermuda'],
    pathogen: 'Eriophyes cynodonis',
    blurb: 'A microscopic eriophyid mite that distorts bermudagrass growth into tufted rosettes.',
    favoredBy: 'Hot, dry weather; thatchy, stressed bermuda.',
    identify: 'Shortened internodes and tufted "witch’s-broom" rosettes at the nodes; yellowing and thinning; damage visible before the mites (need magnification).',
    manage: 'Mow low and remove clippings to reduce populations, reduce thatch, keep turf vigorous; miticides where needed.',
  },
  {
    id: 'two_lined_spittlebug', name: 'Two-lined spittlebug', kind: 'Insect', grasses: ['zoysia', 'bermuda'],
    pathogen: 'Prosapia bicincta',
    blurb: 'A sap-feeder of thatchy warm-season turf whose nymphs hide in frothy "spittle."',
    favoredBy: 'Warm, humid weather and heavy thatch in zoysia and bermuda; southern regions.',
    identify: 'Frothy white spittle masses at the base of the turf; black adults with two orange-red crosslines; stippled, purple-streaked leaves.',
    manage: 'Reduce thatch and excess moisture; treat nymphs with a labeled pyrethroid if damaging.',
  },
  {
    id: 'winter_grain_mite', name: 'Winter grain mite', kind: 'Insect', grasses: ['bent', 'poa', 'bluegrass'],
    pathogen: 'Penthaleus major',
    blurb: 'A cool-season mite that feeds on leaves through the winter, silvering and thinning turf.',
    favoredBy: 'Cool, moist conditions from fall through early spring; active on mild winter days.',
    identify: 'Silvery-gray stippling and thinning; dark-bodied mites with distinctive red-orange legs and a dorsal spot, active on cool overcast days.',
    manage: 'Often self-limits as weather warms. Miticides/insecticides on cool days when damage is significant.',
  },
  {
    id: 'ground_pearls', name: 'Ground pearls', kind: 'Insect', grasses: ['bermuda', 'zoysia'],
    pathogen: 'Margarodes spp.',
    blurb: 'Soil-dwelling scale insects that feed on warm-season roots and are notoriously hard to control.',
    favoredBy: 'Sandy soils in warm/southern climates; drought stress worsens symptoms.',
    identify: 'Irregular yellow-to-dead patches that slowly enlarge; tiny pearl-like cysts attached to roots when you dig.',
    manage: 'No reliable chemical control — maintain vigor, irrigation and fertility to help turf tolerate them; encourage recovery from the edges.',
  },
  {
    id: 'turf_ants', name: 'Ants', kind: 'Insect', grasses: ['bent', 'poa'],
    pathogen: 'Lasius and other species',
    blurb: 'More a smoothness nuisance than a pest — mounds on greens disrupt the roll and dull mower reels.',
    favoredBy: 'Sandy, well-drained greens and tees; warm season.',
    identify: 'Small soil mounds, craters or piles of excavated sand on the putting surface; ant trails.',
    manage: 'Brush/topdress mounds before mowing; labeled baits or insecticides for persistent colonies. Mostly cosmetic.',
  },
]

export function profileById(id) {
  return PROFILES.find((p) => p.id === id) || null
}

// A photo-gallery search for one profile, scoped to turf so results are the real
// thing (we don't ship licensed field photos; this opens current ones instead).
export function photoSearchUrl(p) {
  if (!p) return null
  const scope = p.kind === 'Disease' ? 'turf disease' : p.kind === 'Weed' ? 'turfgrass weed' : 'turf damage'
  const q = `${p.name} ${scope}`
  return `https://www.google.com/search?tbm=isch&q=${encodeURIComponent(q)}`
}

// ── Essential plant nutrients (14 mineral elements) ──────────────────────────
// tier: 'Primary' | 'Secondary' | 'Micro'
export const NUTRIENTS = [
  { sym: 'N', name: 'Nitrogen', tier: 'Primary', mobile: true, role: 'Drives shoot growth, density and color; the nutrient you apply most. Central to proteins and chlorophyll.', deficiency: 'Uniform pale-green to yellow older leaves, thin slow growth. Excess brings lush, disease-prone growth and thatch.', sources: 'Urea, ammonium sulfate, methylene urea, polymer-coated ureas, organics.' },
  { sym: 'P', name: 'Phosphorus', tier: 'Primary', mobile: true, role: 'Energy transfer and rooting; most important for seedlings and establishment.', deficiency: 'Dark green to purple/red tint on older leaves, weak rooting, slow establishment.', sources: 'MAP, DAP, triple superphosphate. Often restricted by law on established turf — soil-test first.' },
  { sym: 'K', name: 'Potassium', tier: 'Primary', mobile: true, role: 'Stress, wear, cold and drought tolerance; water regulation. The "health" nutrient.', deficiency: 'Yellowing/scorching along older-leaf margins, poor stress and disease tolerance.', sources: 'Potassium sulfate, potassium chloride (muriate), potassium nitrate.' },
  { sym: 'Ca', name: 'Calcium', tier: 'Secondary', mobile: false, role: 'Cell-wall structure and root development; rarely deficient in turf.', deficiency: 'Distorted new growth and root tips (rare). Managed more for soil structure/pH than turf response.', sources: 'Gypsum (no pH change), lime (raises pH), calcium nitrate.' },
  { sym: 'Mg', name: 'Magnesium', tier: 'Secondary', mobile: true, role: 'Central atom of chlorophyll; photosynthesis.', deficiency: 'Interveinal yellowing of older leaves (veins stay green); sandy, high-K soils most at risk.', sources: 'Epsom salt (magnesium sulfate), dolomitic lime, K-Mag.' },
  { sym: 'S', name: 'Sulfur', tier: 'Secondary', mobile: false, role: 'Proteins and color; mildly acidifies soil. Increasingly limiting as air deposition has dropped.', deficiency: 'General yellowing resembling nitrogen but on newer leaves; common on sandy soils.', sources: 'Ammonium sulfate, elemental sulfate, gypsum, K-Mag.' },
  { sym: 'Fe', name: 'Iron', tier: 'Micro', mobile: false, role: 'Chlorophyll synthesis; delivers deep green color without pushing growth — a favorite for greens.', deficiency: 'Interveinal yellowing of new leaves; common in high-pH or waterlogged soils.', sources: 'Ferrous sulfate, chelated iron (foliar). Fast, temporary color response.' },
  { sym: 'Mn', name: 'Manganese', tier: 'Micro', mobile: false, role: 'Photosynthesis and enzyme function; linked to disease resistance (e.g. take-all).', deficiency: 'Interveinal chlorosis of young leaves; high-pH sands most prone.', sources: 'Manganese sulfate, chelates (foliar).' },
  { sym: 'Zn', name: 'Zinc', tier: 'Micro', mobile: false, role: 'Enzyme systems and growth-hormone (auxin) production.', deficiency: 'Stunted growth and small, mottled new leaves (rare in turf).', sources: 'Zinc sulfate, chelates.' },
  { sym: 'Cu', name: 'Copper', tier: 'Micro', mobile: false, role: 'Enzyme reactions and lignin; needed in very small amounts.', deficiency: 'Wilted, blue-green new growth and dieback (rare; sandy/organic soils).', sources: 'Copper sulfate, chelates. Easy to over-apply — go by soil test.' },
  { sym: 'B', name: 'Boron', tier: 'Micro', mobile: false, role: 'Cell-wall formation and pollen/seed development; narrow safe range.', deficiency: 'Distorted, brittle new growth. Toxicity is a bigger risk than deficiency — apply carefully.', sources: 'Borax, Solubor (very low rates).' },
  { sym: 'Mo', name: 'Molybdenum', tier: 'Micro', mobile: false, role: 'Nitrogen metabolism (nitrate reduction); needed in the smallest amount of all.', deficiency: 'Pale, nitrogen-like yellowing; more likely on acidic soils.', sources: 'Sodium molybdate (trace rates); often corrected by raising low pH.' },
  { sym: 'Cl', name: 'Chlorine', tier: 'Micro', mobile: true, role: 'Osmosis, water regulation and disease suppression.', deficiency: 'Wilting and chlorosis (very rare — usually plentiful from water and fertilizers).', sources: 'Potassium chloride, irrigation water.' },
  { sym: 'Ni', name: 'Nickel', tier: 'Micro', mobile: true, role: 'Part of the urease enzyme that lets plants use urea nitrogen. The most recently confirmed essential element.', deficiency: 'Extremely rare in turf; urea toxicity symptoms if truly deficient.', sources: 'Trace amounts in most fertilizers and soils — rarely applied.' },
]
